name: matomo_tracker
description: A fully cross-platform wrap of the Matomo tracking client for
  Flutter, using the Matomo API.
version: 6.1.1
homepage: https://github.com/Floating-Dartists/matomo-tracker
repository: https://github.com/Floating-Dartists/matomo-tracker
issue_tracker: https://github.com/Floating-Dartists/matomo-tracker/issues
topics:
  - matomo
  - analytics

environment:
  sdk: ">=3.4.1 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  clock: ^1.1.2
  collection: ^1.19.1
  device_info_plus: ">=11.3.3 <14.0.0"
  flutter:
    sdk: flutter
  http: ^1.6.0
  package_info_plus: ">=8.3.0 <11.0.0"
  shared_preferences: ^2.5.5
  uuid: ^4.5.3

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  meta: ^1.18.0
  mocktail: ^1.0.5
